Repository puppetlabs/device_manager, pull requests merged in 2019-06, with the labels that each got.

#48 (FM-8238, FM-8137) Dependency fixes
  .sync.yml
  .vscode/extensions.json
  Gemfile
  metadata.json
Labels: bugfix

#51 (FM-8015) adding tag to aid with Forge searches
  metadata.json
Labels: enhancement

#52 pdksync - pdksync_heads/master-0-g7b1d6ae
  .rubocop.yml
  Rakefile
  metadata.json
Labels: maintenance

#53 (maint) changing the include to use new rsapi manifests
  spec/acceptance/configure_spec.rb
Labels: maintenance
